name: Lint Changed Python Files

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pre-commit and ruff
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Run ruff on changed Python files
        run: |
          # Fetch the previous commit for comparison
          git fetch origin main

          # Get the list of changed Python files
          CHANGED_FILES=$(git diff --name-only origin/main | grep -E '\.py$')

          if [ -z "$CHANGED_FILES" ]; then
            echo "No Python files changed."
            exit 0
          fi

          # Run pre-commit on the changed Python files
          pre-commit run ruff --files $CHANGED_FILES

      - name: Display pre-commit configuration
        run: cat .pre-commit-config.yaml
